# Generated by Selenium IDE
import pytest

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait

class TestUS11():
    BASE_URL = "https://tobeto.com/giris"
    EMAIL = "ozgecam@outlook.com"
    PASSWORD = "ozge-cam-5595"
    WAIT_TIME = 20

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.get(self.BASE_URL)
        self.driver.maximize_window()

    def teardown_method(self, method):
        self.driver.quit()

    def login(self, email, password):
        # Giriş ekranı alanına gitme methodu.
        WebDriverWait(self.driver, self.WAIT_TIME).until(EC.visibility_of_element_located((By.NAME, "email"))).send_keys(email)
        WebDriverWait(self.driver, self.WAIT_TIME).until(EC.visibility_of_element_located((By.NAME, "password"))).send_keys(password)
        WebDriverWait(self.driver, self.WAIT_TIME).until(EC.element_to_be_clickable((By.XPATH, "//button[@type='submit']"))).click()
        WebDriverWait(self.driver, self.WAIT_TIME).until(EC.element_to_be_clickable((By.XPATH, "//a[contains(text(),'Değerlendirmeler')]"))).click()

    def raporlar(self):
        # Bu testler değerlendirmeler alanında rapor görüntüleme işlemi gerçekleşmektedir.
        WebDriverWait(self.driver, self.WAIT_TIME).until(EC.element_to_be_clickable((By.XPATH,"//a[contains(text(),'Raporu Görüntüle')]"))).click()

    @pytest.mark.parametrize("email, password", [(EMAIL, PASSWORD)]) 
    def test_US11_TC1(self, email, password):
        self.login(email, password)
        self.raporlar()
        assert "Tobeto İşte Başarı Modeli" in self.driver.title, "Rapor Görüntülenemedi."


    # Analiz raporunda bulunan yetkinlik özniteliklerinin alt butonla açılması 
    @pytest.mark.parametrize("email, password", [(EMAIL,PASSWORD)]) 
    def test_US11_UC2_1(self, email, password):
        self.login(email, password)
        self.raporlar()
       
        self.driver.execute_script("window.scrollTo(0,400)")
        WebDriverWait(self.driver, self.WAIT_TIME).until(EC.element_to_be_clickable((By.XPATH,"(//button[@type='button'])[4]"))).click()
        """ assert edilememektedir araştırılıyor."""
        
       



 
  
