# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUS09Profilbilgilerinigrntlmesibeklenir():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_uS9TC1Kaytlprofilbilgilerineulalabilirvegrntlenmesibeklenir(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profilim\')]").click()
    self.driver.close()
  
  def test_uS9TC2ProfiliPaylaButonununKontrol(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Profilim").click()
    self.driver.find_element(By.ID, "dropdown-basic").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-switch-bg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ms-3").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".toast-body").text == "• Url kopyalandı."
  
  def test_uS9TC3SertifikaKontrolveDosyannindirilmesibeklenir(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profilim\')]").click()
    self.driver.execute_script("window.scrollTo(0,1333.3333740234375)")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".cursor-pointer:nth-child(1) > .d-flex").click()
    self.vars["C:\Users\Busraa\Downloads"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(${C:\\Users\\Busraa\\Downloads})
    self.driver.close()
  
  def test_uS9TC4SosyalMedyaHesaplarnnGrntlenmesibeklenir(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profilim\')]").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".cv-linkedin").click()
    self.vars["https://www.linkedin.com/in/ozgeedc1610/"] = self.wait_for_window(2000)
    self.driver.close()
  
  def test_uS9TC5teBaarmAnalizRaporuGrntlenmelidir(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profilim\')]").click()
    self.driver.execute_script("window.scrollTo(0,248)")
    self.driver.find_element(By.XPATH, "//canvas").click()
    self.driver.close()
  
