# Generated by Selenium IDE
from asyncio import sleep
from typing import Literal
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.by import By as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUS09Profilbilgilerinigrntlmesibeklenir():
  def setup_method(self,):
    self.driver = webdriver.Chrome()
    self.driver.get("https://tobeto.com/giris")
    self.driver.maximize_window()
    
  
  def teardown_method(self,):
    self.driver.quit()

  # Kullanıcı , profil bilgilerini düzenleyebileceği alanı görüntülemesi beklenir.
  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")])  
  def test_uS12TC1(self, email: Literal['ozgecam@outlook.com'], password: Literal['ozge-cam-5595']):
    WebDriverWait(self.driver,10).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)

    
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    
    WebDriverWait(self.driver, -7).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()

    sleep(25)

    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located((By.CLASS_NAME, "btn.p-0.fw-normal.b-r-35.text-end.d-flex.align-items-center")))

    # Eleman çakışması sorun oluşturuyorsa, JavaScript kullanarak butona tıklayın
    buton = self.driver.find_element(By.CLASS_NAME, "btn.p-0.fw-normal.b-r-35.text-end.d-flex.align-items-center")
    self.driver.execute_script("arguments[0].click();", buton)
   
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "span:nth-child(3) > svg")))
    kbilgilerbuton=self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg")
    kbilgilerbuton.click()
    #Sayfanın görüntülenip görüntülenmediğini Link ile doğrulanmıyor , içerisinde ki yazılarla assert text yapılamıyor.
   
    
    
   #Kullanıcının , Deneyimlerini düzenleyebileceği alanın görüntülenmesi beklenir. OK
   #Giriş yap ekranlarında 2 adet başarılı giriş yapılmıştır bildirimi alınmaktadır. Bu bildirimin sonucunda ise Kod hata vermektedir

  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")]) 
  def test_uS12TC2(self, email: Literal['ozgecam@outlook.com'], password: Literal['ozge-cam-5595']):

    WebDriverWait(self.driver,10).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)

    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
    sleep(15)

    #BAŞARILI GİRİŞ YAPILMIŞTIR BUTONUN ÜZERİNE GELMEKTEDİR. BİLDİRİM 2 KEZ ÇIKMAKTADIR. CANLIDA BUTON HIZLICA KAYBOLMAKTADIR. 

    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH,"(//button[@type='button'])[4]")))
    close1=self.driver.find_element(By.XPATH,"(//button[@type='button'])[4]")
    close1.click()
    
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.CLASS_NAME,"btn.p-0.fw-normal.b-r-35.text-end.d-flex.align-items-center")))
    sleep(5)
    profilbuton = self.driver.find_element(expected_conditions.CLASS_NAME,"btn.p-0.fw-normal.b-r-35.text-end.d-flex.align-items-center")
    profilbuton.click()

    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH,"//a[contains(text(),'Profil Bilgileri')]")))
    profilbuton1 = self.driver.find_element(expected_conditions.XPATH, "//a[contains(text(),'Profil Bilgileri')]")
    profilbuton1.click()

    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "span:nth-child(3) > svg")))
    kbilgilerbuton=self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg")
    kbilgilerbuton.click()

    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located((By.XPATH,"//span[contains(.,\'Deneyimlerim\')]")))
    deneyimb = self.driver.find_element(By.XPATH, "//span[contains(.,\'Deneyimlerim\')]")
    deneyimb.click()
    #assert EC.visibility_of_element_located((By.XPATH, "//span[contains(.,\'Deneyimlerim\')]"))
    
  # 
  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")])
  def test_uS12TC3EitimHayatmbalnnolduualannnalmas(self,email: Literal['ozgecam@outlook.com'],password: Literal['ozge-cam-5595']):
    WebDriverWait(self.driver,10).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)

    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
    #sleep(15)
    # sayfayı bu kısımdan sonra istemsizce kaydırmaktadır.
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH,"(//button[@type='button'])[4]")))
    close1=self.driver.find_element(By.XPATH,"(//button[@type='button'])[4]")
    close1.click()

    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH,"(//button[@type=\'button\'])[4]")))
    p_buton = self.driver.find_element(By.XPATH,"(//button[@type=\'button\'])[4]")
    sleep(15)
    p_buton.click()

    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[4]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div/nav/div/div/div/div[2]/button/div[2]/p").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Eğitim Hayatım\')]").click()
    self.driver.close()
  








  def test_uS12TC4Yetkinliklerimbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[4]").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Yetkinliklerim\')]").click()
    self.driver.close()
  
  def test_uS12TC5Sertifikalarmbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Sertifikalarım\')]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div/main/section/div/div/div[2]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-text").text == "Sertifikalarım"
    self.driver.close()
  
  def test_uS12TC6MedyaHesaplarmbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    element = self.driver.find_element(By.CSS_SELECTOR, ".signup")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Medya Hesaplarım\')]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div/main/section/div/div/div[2]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(4)").text == "En fazla 3 adet medya seçimi yapılabilir."
    self.driver.close()
  
  def test_uS12TC7YabancDillerimbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Yabancı Dillerim\')]").click()
    self.driver.close()
  
  def test_uS12TC8Ayarlarbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Ayarlar\')]").click()
    self.driver.close()
  
