# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUS09Profilbilgilerinigrntlmesibeklenir():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get("https://tobeto.com/giris")
    self.driver.maximize_window()
    #self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  

   # Kullanıcı profil bilgilerinin güncellenmesi ve görüntülenmesi
   
  def test_uS9TC1(self):
   
    WebDriverWait(self.driver,10).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys("ozgecam@outlook.com")

    
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password = self.driver.find_element(By.NAME,"password")
    password.send_keys("ozge-cam-5595") 
    
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()

    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH, "//a[contains(text(),\'Profilim\')]")))
    ProfilimButon = self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profilim\')]")
    ProfilimButon.click()

   
  
  def test_uS9TC2ProfiliPaylaButonununKontrol(self):

    WebDriverWait(self.driver,10).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys("ozgecam@outlook.com")

    
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password = self.driver.find_element(By.NAME,"password")
    password.send_keys("ozge-cam-5595") 
    
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()

    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH, "//a[contains(text(),\'Profilim\')]")))
    ProfilimButon = self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profilim\')]")
    ProfilimButon.click()
   
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.NAME,"dropdown-basic")))
    profilipaylas = self.driver.find_element(By.ID, "dropdown-basic")
    profilipaylas.click()

    self.driver.find_element(By.CSS_SELECTOR, ".react-switch-bg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ms-3").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".toast-body").text == "• Url kopyalandı."
  
  def test_uS9TC3SertifikaKontrolveDosyannindirilmesibeklenir(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profilim\')]").click()
    self.driver.execute_script("window.scrollTo(0,1333.3333740234375)")
    #self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".cursor-pointer:nth-child(1) > .d-flex").click()
    #self.vars["C:\Users\Busraa\Downloads"] = self.wait_for_window(2000)
    #self.vars["root"] = self.driver.current_window_handle
    #self.driver.switch_to.window(${C:\\Users\\Busraa\\Downloads})
    self.driver.close()
  
  def test_uS9TC4SosyalMedyaHesaplarnnGrntlenmesibeklenir(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profilim\')]").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".cv-linkedin").click()
    self.vars["https://www.linkedin.com/in/ozgeedc1610/"] = self.wait_for_window(2000)
    self.driver.close()
  
  def test_uS9TC5teBaarmAnalizRaporuGrntlenmelidir(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profilim\')]").click()
    self.driver.execute_script("window.scrollTo(0,248)")
    self.driver.find_element(By.XPATH, "//canvas").click()
    self.driver.close()
  
