# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUS11BireyselDeerlendirmeEkrannnGrntlenmesi():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uS11TC1TestsonucundakullancyaaitAnalizRaporugrntlenmelidir(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "//section[4]/div/div/div[2]/div/button").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Raporu Görüntüle\')]").click()
    self.driver.close()
  #Analiz raporunda bulunan yetkinlik özniteliklerinin alt butonla açılması 
  def test_uS11UC2_1(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.execute_script("window.scrollTo(0,528.888916015625)")
    self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div/main/div/section[4]/div/div/div[2]/div/button").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Raporu Görüntüle\')]").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[4]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'collapse8\']/div/div").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#collapse8 p:nth-child(3) > span").text == "Tüm bu dönüşüm süreci içinde; yeni dünyayı anlamış, bu dünyada başarılı olabilecek dijital ve teknoloji yetkinliklerine sahip adayların istihdamı kuşkusuz daha kolay. Bu konudaki gelişim ihtiyacı sadece istihdamla ilgili de değil çünkü bu beceriler gündelik yaşamda da çok önemli hale gelmiş durumda. İnterneti iyi kullanan, aradığı tüm bilgilere ulaşabilen, ihtiyacına göre dijital uygulamaları arayıp bulan, siber dünyada güvenliğini koruyabilen tüm bireyler birçok alanda öne çıkıyor. Ayrıca bu dünya fırsatlar dünyasıdır. Yeni mecralar, yeni işler, yeni para kazanma biçimleri ortaya çıkarken bu fırsatları ancak yeterli donanıma sahip bireyler yakalayabilecek. Tüm bu açılardan bakıldığında bu yetkinlik, diğer tüm yetkinliklerin gücünü artırması açısından önemli. "
    self.driver.close()
  
  def test_uS11UC22YetkinliklerinneminiAnlatanAltBalklarnGrntlenmesivebalklarnkapatlmasbeklenir(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".pack-bg-3 > .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div/main/div/section[4]/div/div/div[2]/div/button").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Raporu Görüntüle\')]").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[4]").click()
    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[4]").click()
    self.driver.close()
  
