# Generated by Selenium IDE
from asyncio import sleep
from typing import Literal
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.by import By as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUS09Profilbilgilerinigrntlmesibeklenir():
  def setup_method(self,):
    self.driver = webdriver.Chrome()
    self.driver.get("https://tobeto.com/giris")
    self.driver.maximize_window()
    
  
  def teardown_method(self,):
    self.driver.quit()

  # Kullanıcı , profil bilgilerini düzenleyebileceği alanı görüntülemesi beklenir.
  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")])  
  def test_uS12TC1(self, email: Literal['ozgecam@outlook.com'], password: Literal['ozge-cam-5595']):

    WebDriverWait(self.driver,10).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    self.driver.execute_script("window.scrollTo(0,600)")
    profilbasla = self.driver.find_element(By.XPATH,"//button[contains(.,'Başla')]")
    profilbasla.click()
    #kişisel bilgilerim düzenleme alanı direk açıldığından sayfanın açılması ile ilgili assert eklenicektir.
   
    
    
   #Kullanıcının , Deneyimlerini düzenleyebileceği alanın görüntülenmesi beklenir. OK
   

  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")]) 
  def test_uS12TC2(self, email: Literal['ozgecam@outlook.com'], password: Literal['ozge-cam-5595']):

    WebDriverWait(self.driver,10).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    self.driver.execute_script("window.scrollTo(0,400)")
    profilbasla = self.driver.find_element(By.XPATH,"//button[contains(.,'Başla')]")
    profilbasla.click()
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH,"//span[contains(.,\'Deneyimlerim\')]")))
    deneyimb = self.driver.find_element(By.XPATH, "//span[contains(.,\'Deneyimlerim\')]")
    deneyimb.click()
    
    
  # Eğitim Hayatım alanının görüntülenmesi 
  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")])
  def test_uS12TC3(self,email: Literal['ozgecam@outlook.com'],password: Literal['ozge-cam-5595']):
    WebDriverWait(self.driver,10).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)

    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    #Bu alanada sayfa istemsiz şekilde aşağ kaymaktadır.
    
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
  
    self.driver.execute_script("window.scrollTo(0,600)")
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    profilbasla = self.driver.find_element(By.XPATH,"//button[contains(.,'Başla')]")
    profilbasla.click()
    WebDriverWait(self.driver,15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//span[contains(.,'Eğitim Hayatım')]")))
    egitim = self.driver.find_element(By.XPATH,"//span[contains(.,\'Eğitim Hayatım\')]")
    egitim.click()


  #Yetkinliklerim alanının görüntülenmesi
  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")]) 
  def test_uS12TC4(self,email: Literal['ozgecam@outlook.com'],password: Literal['ozge-cam-5595']):
    WebDriverWait(self.driver,5).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)

    WebDriverWait(self.driver,5).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
    sleep(15)
    
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    self.driver.execute_script("window.scrollTo(0,500)")
    profilbasla = self.driver.find_element(By.XPATH,"//button[contains(.,'Başla')]")
    profilbasla.click()

    sleep(10)
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//span[contains(.,\'Yetkinliklerim\')]")))
    yetkinlik = self.driver.find_element(By.XPATH, "//span[contains(.,\'Yetkinliklerim\')]")
    yetkinlik.click()
    
    #Sertifikaları düzenleme alanının görüntülenmesi.
  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")]) 
  def test_uS12TC5(self,email: Literal['ozgecam@outlook.com'],password: Literal['ozge-cam-5595'],):
  
    WebDriverWait(self.driver,5).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)

    WebDriverWait(self.driver,5).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
    WebDriverWait(self.driver, 20 ).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    self.driver.execute_script("window.scrollTo(0,500)")
    profilbasla = self.driver.find_element(By.XPATH,"//button[contains(.,'Başla')]")
    profilbasla.click()
  
    WebDriverWait(self.driver,20).until(expected_conditions.visibility_of_element_located((By.XPATH,"//span[contains(.,\'Sertifikalarım\')]")))
    sertifika = self.driver.find_element(By.XPATH, "//span[contains(.,\'Sertifikalarım\')]")
    sertifika.click()
    


  #Kullanıcı sosyal medya hesaplarının düzenlenme alanının görüntülenmesi 
  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")]) 
  def test_uS12TC6(self,email: Literal['ozgecam@outlook.com'],password: Literal['ozge-cam-5595']):
    WebDriverWait(self.driver,3).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)

    WebDriverWait(self.driver,3).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    
    WebDriverWait(self.driver, 3).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    self.driver.execute_script("window.scrollTo(0,600)")
    
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    profilbasla = self.driver.find_element(By.XPATH,"//button[contains(.,'Başla')]")
    profilbasla.click()
   
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.XPATH,"//span[contains(.,\'Medya Hesaplarım\')]")))
    medya =self.driver.find_element(By.XPATH, "//span[contains(.,\'Medya Hesaplarım\')]")
    medya.click()
    
    
  #Kullanıcının yabancı dil bilgilerini ekleyebileceği alanın görüntülenmesi
  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")])
  def test_uS12TC7(self,email: Literal['ozgecam@outlook.com'],password: Literal['ozge-cam-5595']):
    WebDriverWait(self.driver,3).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)

    WebDriverWait(self.driver,3).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    
    WebDriverWait(self.driver, 3).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    self.driver.execute_script("window.scrollTo(0,600)")
    
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    profilbasla = self.driver.find_element(By.XPATH,"//button[contains(.,'Başla')]")
    profilbasla.click()
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.XPATH,"//span[contains(.,\'Yabancı Dillerim\')]")))
    yabancidil=self.driver.find_element(By.XPATH, "//span[contains(.,\'Yabancı Dillerim\')]")
    yabancidil.click()
    
  # Kullanıcı , şifre değişikliliği işlemleri
  @pytest.mark.parametrize("email, password", [("ozgecam@outlook.com", "ozge-cam-5595")])
  def test_uS12TC8(self,email: Literal['ozgecam@outlook.com'],password: Literal['ozge-cam-5595']):
    WebDriverWait(self.driver,3).until(expected_conditions.visibility_of_element_located((By.NAME,"email")))
    username = self.driver.find_element(By.NAME,"email")
    username.send_keys(email)

    WebDriverWait(self.driver,3).until(expected_conditions.visibility_of_element_located((By.NAME,"password")))
    password_field = self.driver.find_element(By.NAME,"password")
    password_field.send_keys(password) 
    
    WebDriverWait(self.driver, 3).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[@type=\'submit\']")))
    girisYap = self.driver.find_element(By.XPATH,"//button[@type=\'submit\']")
    girisYap.click()
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    self.driver.execute_script("window.scrollTo(0,600)")
    
    WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located((By.XPATH,"//button[contains(.,'Başla')]")))
    profilbasla = self.driver.find_element(By.XPATH,"//button[contains(.,'Başla')]")
    profilbasla.click()
    WebDriverWait(self.driver, 15).until(expected_conditions.visibility_of_element_located((By.XPATH,"//span[contains(.,\'Ayarlar\')]")))
    ayarlar = self.driver.find_element(By.XPATH, "//span[contains(.,\'Ayarlar\')]")
    ayarlar.click()
    
  
