# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUS12KullancProfiliOluturma():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uS12TC1KiiselBilgilerimbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1536, 835)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[4]").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.close()
  
  def test_uS12TC2Deneyimlerimbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[4]").click()
    self.driver.find_element(By.XPATH, "//img[contains(@src,\'https://tobeto-private.s3.cloud.ngn.com.tr/user-profile-photo/24099.png?AWSAccessKeyId=ALMS%3Aalms-storage%40advancity.com.tr&Expires=1716982793&Signature=ey9iTq2o0H1j6m%2FApbCK3X1lMvA%3D\')]").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Deneyimlerim\')]").click()
    self.driver.close()
  
  def test_uS12TC3EitimHayatmbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    element = self.driver.find_element(By.CSS_SELECTOR, ".login")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[4]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div/nav/div/div/div/div[2]/button/div[2]/p").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Eğitim Hayatım\')]").click()
    self.driver.close()
  
  def test_uS12TC4Yetkinliklerimbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[4]").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Yetkinliklerim\')]").click()
    self.driver.close()
  
  def test_uS12TC5Sertifikalarmbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Sertifikalarım\')]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div/main/section/div/div/div[2]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-text").text == "Sertifikalarım"
    self.driver.close()
  
  def test_uS12TC6MedyaHesaplarmbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    element = self.driver.find_element(By.CSS_SELECTOR, ".signup")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Medya Hesaplarım\')]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'__next\']/div/main/section/div/div/div[2]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(4)").text == "En fazla 3 adet medya seçimi yapılabilir."
    self.driver.close()
  
  def test_uS12TC7YabancDillerimbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Yabancı Dillerim\')]").click()
    self.driver.close()
  
  def test_uS12TC8Ayarlarbalnnolduualannnalmas(self):
    self.driver.get("https://tobeto.com/giris")
    self.driver.set_window_size(1552, 849)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ozgecam@outlook.com")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("ozge-cam-5595")
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(3) > svg").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Profil Bilgileri\')]").click()
    self.driver.find_element(By.XPATH, "//span[contains(.,\'Ayarlar\')]").click()
    self.driver.close()
  
